### ISSUE TITLE
Better support for has_one relations

### ISSUE THREAD

**Issue by pedro-gutierrez** [Gravity-Core/graphism#27]
Currently they produce errors such as, most likely because they are not included in the Ecto schema.

```
Request: POST /graphiql
** (exit) an exception was raised:
    ** (RuntimeError) Valid association xxxx not found on schema ...
Got: nil
        (dataloader 1.0.8) lib/dataloader/ecto.ex:476: Dataloader.Source.Dataloader.Ecto.chase_down_queryable/2
        (dataloader 1.0.8) lib/dataloader/ecto.ex:499: Dataloader.Source.Dataloader.Ecto.get_keys/2
        (dataloader 1.0.8) lib/dataloader/ecto.ex:439: Dataloader.Source.Dataloader.Ecto.load/3
        (elixir 1.11.4) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
        (dataloader 1.0.8) lib/dataloader.ex:128: Dataloader.load_many/4
        (absinthe 1.5.5) lib/absinthe/resolution/helpers.ex:356: Absinthe.Resolution.Helpers.do_dataloader/5
        (absinthe 1.5.5) lib/absinthe/resolution.ex:209: Absinthe.Resolution.call/2
        (absinthe 1.5.5) lib/absinthe/phase/document/execution/resolution.ex:230: Absinthe.Phase.Document.Execution.Resolution.reduce_resolution/1
```
```

**Comment by pedro-gutierrez** [comment]
we are dropping has_one relations altogether
